export const CREATE_POST = 'POSTS/CREATE'
export const CREATE_POST_SUCCESS = 'POSTS/CREATE_SUCCESS'
export const CREATE_POST_ERROR = 'POSTS/CREATE_ERROR'
export const DELETE_POST = 'POSTS/DELETE'
export const FETCH_POSTS = 'POSTS/FETCH'
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR';

export const SET_SEARCH_VALUE = 'SEARCHVALUE/SET'
export const RESET_SEARCH_VALUE = 'SEARCHVALUE/RESET'
