export const CREATE_POST = 'POSTS/CREATE'
export const DELETE_POST = 'POSTS/DELETE'
export const FETCH_POSTS = 'POSTS/FETCH'

export const SET_SEARCH_VALUE = 'SEARCHVALUE/SET'
export const RESET_SEARCH_VALUE = 'SEARCHVALUE/RESET'
